name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Set up SSH and known hosts
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      # Verify deployment source directory
      - name: Verify Deployment Directory
        run: |
          if [ ! -d "./" ] || [ -z "$(ls -A ./)" ]; then
            echo "Source directory is empty. Aborting deployment.";
            exit 1;
          fi
      # Deploy files using rsync
      - name: Deploy to VPS
        run: |
          rsync -avz \
            -e 'ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no' \
            --exclude '.git*' \
            --exclude 'node_modules' \
            ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/html/
      # Reload Apache after deploying files
      - name: Post-deploy commands
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} '
            sudo systemctl reload apache2
          '
