name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger deployment on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up SSH
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Ensure that the server's SSH host is in known_hosts
        ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

    # Test SSH connection
    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -v root@$VPS_IP "echo 'SSH connection successful'"

    # Deploy to VPS (Apache2, root user)
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@$VPS_IP <<EOF
          cd /var/www/html  # Assuming your website is served from Apache's default directory
          git pull origin main  # or other commands for deployment
          # You can also add commands like `composer install`, `npm install` etc.
          # Example: restart Apache if needed
          systemctl restart apache2
        EOF
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
